In [21]:
class dijkstra:
    
    def __init__(self,n,start,goal,A):
        self.n = n
        self.start = start
        self.goal = goal
        self.A = A
        self.S = np.array([])
        self.nonS = np.arange(n)
        self.d = np.tile([10000],n)
        self.d[start] = 0
        self.p = np.tile([-1],n)

        
    def check(self):
        print ("n:" ,self.n)
        print ("start:",self.start)
        print ("goal:",self.goal)
        print ("A:",self.A)
        print ("S:",self.S)
        print ("nonS",self.nonS)
        print ("d:",self.d)
        print ("p:",self.p)

    #vの選択
    def select_v(self,nonS,d):
        _mind = 100000
        _mini = 0
    
        for i in self.nonS:
            if self.d[i] < _mind:
                _mind = self.d[i]
                _mini = i
        return _mini

    #jを見つける
    def search_j (self,nonS,A,v):
        j = []
        for i in self.nonS:
            if self.A[v][i] > 0:
                j.append(i)
        return j

    #ダイクストラ法
    def culculation(self):
        while (len(self.nonS) is not 0):

            v = self.select_v(self.nonS,self.d)
            self.S = np.append(self.S,v)
            self.S = np.sort(self.S)
    
            index = np.where(self.nonS == v)
            self.nonS = np.delete(self.nonS,index)
    
            j = self.search_j(self.nonS,self.A,v)
            for i in j:
                if self.d[i] > self.d[v] + self.A[v][i]:
                    self.d[i] = self.d[v] + self.A[v][i]
                    self.p[i] = v

            print("S:",self.S , " nonS:", self.nonS)
            print("p:",self.p , " d:",self.d)
            print("")

In [22]:
#初期値の設定
import numpy as np

n = 5
start = 0
goal = 4

#A: エッジの長さを示す行列
A = np.array([[0,50,80,0,0],[0,0,20,15,0],[0,0,0,10,15],[0,0,0,0,30],[0,0,0,0,0]])

In [23]:
a = dijkstra(n,start,goal,A)
a.check()

n: 5
start: 0
goal: 4
A: [[ 0 50 80  0  0]
 [ 0  0 20 15  0]
 [ 0  0  0 10 15]
 [ 0  0  0  0 30]
 [ 0  0  0  0  0]]
S: []
nonS [0 1 2 3 4]
d: [    0 10000 10000 10000 10000]
p: [-1 -1 -1 -1 -1]


In [24]:
a.culculation()

S: [ 0.]  nonS: [1 2 3 4]
p: [-1  0  0 -1 -1]  d: [    0    50    80 10000 10000]

S: [ 0.  1.]  nonS: [2 3 4]
p: [-1  0  1  1 -1]  d: [    0    50    70    65 10000]

S: [ 0.  1.  3.]  nonS: [2 4]
p: [-1  0  1  1  3]  d: [ 0 50 70 65 95]

S: [ 0.  1.  2.  3.]  nonS: [4]
p: [-1  0  1  1  2]  d: [ 0 50 70 65 85]

S: [ 0.  1.  2.  3.  4.]  nonS: []
p: [-1  0  1  1  2]  d: [ 0 50 70 65 85]



In [25]:
a.check()

n: 5
start: 0
goal: 4
A: [[ 0 50 80  0  0]
 [ 0  0 20 15  0]
 [ 0  0  0 10 15]
 [ 0  0  0  0 30]
 [ 0  0  0  0  0]]
S: [ 0.  1.  2.  3.  4.]
nonS []
d: [ 0 50 70 65 85]
p: [-1  0  1  1  2]
